### ISSUE TITLE
Фигня с паролев в котором есть :

### ISSUE THREAD

**Issue by o0omega** [Obl1Que/QFARM#2]
Если в пароле есть : то оно и всё что после просто не читается при добавлении ака
т.е. к примеру логин 34243a пароль b324:232
добавляем
34243a:b324:232
записывает 
34243
b324

**Comment by Obl1Que** [comment]
В пароле стим не может быть знака :

**Comment by o0omega** [comment]
> В пароле стим не может быть знака :

Может, ты путаешь с ником
В любом случае в беседе ili ya уже скинул фикс
